/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Test */

#ifndef _Included_Test
#define _Included_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Test
 * Method:    testString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Test_testString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Test
 * Method:    testInt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Test_testInt
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
